# Building a Custom Classifier

In [29]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression, SGDClassifier

In [2]:
data = pd.DataFrame([("i love spending time with my friends and family", "positive"),
                     ("that was the best meal i've ever had in my life", "positive"),
                     ("i feel so grateful for everything i have in my life", "positive"),
                     ("i received a promotion at work and i couldn't be happier", "positive"),
                     ("watching a beautiful sunset always fills me with joy", "positive"),
                     ("my partner surprised me with a thoughtful gift and it made my day", "positive"),
                     ("i am so proud of my daughter for graduating with honors", "positive"),
                     ("listening to my favorite music always puts me in a good mood", "positive"),
                     ("i love the feeling of accomplishment after completing a challenging task", "positive"),
                     ("i am excited to go on vacation next week", "positive"),
                     ("i feel so overwhelmed with work and responsibilities", "negative"),
                     ("the traffic during my commute is always so frustrating", "negative"),
                     ("i received a parking ticket and it ruined my day", "negative"),
                     ("i got into an argument with my partner and we're not speaking", "negative"),
                     ("i have a headache and i feel terrible", "negative"),
                     ("i received a rejection letter for the job i really wanted", "negative"),
                     ("my car broke down and it's going to be expensive to fix", "negative"),
                     ("i'm feeling sad because i miss my friends who live far away", "negative"),
                     ("i'm frustrated because i can't seem to make progress on my project", "negative"),
                     ("i'm disappointed because my team lost the game", "negative")
                    ],
                    columns=['text', 'sentiment'])

## Logistic Regression
Is a classification algorithm, logistic regresion's goal is to predict categories (classes)

SHuffling the dataset makes sure we have a good mix of positive and negative sentences instead of having them grouped

In [3]:
data = data.sample(frac=1).reset_index(drop=True)

In [4]:
data

                                                 text sentiment
0   i received a promotion at work and i couldn't ...  positive
1   i feel so overwhelmed with work and responsibi...  negative
2               i have a headache and i feel terrible  negative
3   the traffic during my commute is always so fru...  negative
4   i'm feeling sad because i miss my friends who ...  negative
5   i am so proud of my daughter for graduating wi...  positive
6   i love the feeling of accomplishment after com...  positive
7     i love spending time with my friends and family  positive
8      i'm disappointed because my team lost the game  negative
9   my partner surprised me with a thoughtful gift...  positive
10  i got into an argument with my partner and we'...  negative
11   i received a parking ticket and it ruined my day  negative
12  listening to my favorite music always puts me ...  positive
13  watching a beautiful sunset always fills me wi...  positive
14  i received a rejection letter for the job i re...  negative
15           i am excited to go on vacation next week  positive
16  i feel so grateful for everything i have in my...  positive
17    that was the best meal i've ever had in my life  positive
18  i'm frustrated because i can't seem to make pr...  negative
19  my car broke down and it's going to be expensi...  negative

In [5]:
X = data['text']
y = data['sentiment']

In [6]:
# text vectorization to bow - CountVectorizer
countvec = CountVectorizer()
countvec_fit = countvec.fit_transform(X)
bag_of_words = pd.DataFrame(countvec_fit.toarray(), columns = countvec.get_feature_names_out())

In [14]:
bag_of_words

,accomplishment,after,always,am,an,and,argument,at,away,be,...,vacation,ve,wanted,was,watching,we,week,who,with,work
0,0,0,0,0,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
5,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
10,0,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,1,0,0,1,0
11,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
15,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [10]:
# split into train and test data
X_train, X_test, y_train, y_test = train_test_split(bag_of_words, y, test_size=0.3, random_state = 7)

## Logistic Regression

##### Features: input data (X)
##### Labels: output data (y)
##### 
##### Training: 70% The data use for learning 
##### Testing: 30% The data use for evaluation

In [11]:
lr = LogisticRegression(random_state=1).fit(X_train, y_train)

In [15]:
y_pred_lr = lr.predict(X_test)

##### *** Accuracy_score() gives the percentage of sentences the model predict correctly ***

In [16]:
accuracy_score(y_pred_lr, y_test)

0.5

In [17]:
y_pred_lr

array(['positive', 'positive', 'positive', 'positive', 'negative',
       'negative'], dtype=object)

In [18]:
y_test

1     negative
17    positive
2     negative
5     positive
11    negative
0     positive
Name: sentiment, dtype: object

In [19]:
print(classification_report(y_test, y_pred_lr, zero_division=0))

              precision    recall  f1-score   support

    negative       0.50      0.33      0.40         3
    positive       0.50      0.67      0.57         3

    accuracy                           0.50         6
   macro avg       0.50      0.50      0.49         6
weighted avg       0.50      0.50      0.49         6

##### Precision: out of all the sentences the model predicted as positive or negative, what proportion were actually correct
##### Recall: out of all the sentences that truly belong to a class, what proportion did the model correctly find
##### F1-score: a single number (from 0 to 1) that combines precision and recall (balance between precision and score)

## Naive Bayes

###### Naive Bayes looks at how often certain words apper in each group. Then, it uses these counts to estimate the probability that a new review belongs to each group.
###### Naives combines the word counts mathematically and then predicts the most likely class for a new text
###### Naive Bayes assumes that each word in a review is independent of the others

In [25]:
nb = MultinomialNB().fit(X_train, y_train)

In [26]:
y_pred_nb = nb.predict(X_test)

In [27]:
accuracy_score(y_pred_nb, y_test)

0.5

In [28]:
print(classification_report(y_test, y_pred_nb, zero_division=0))

              precision    recall  f1-score   support

    negative       0.50      0.33      0.40         3
    positive       0.50      0.67      0.57         3

    accuracy                           0.50         6
   macro avg       0.50      0.50      0.49         6
weighted avg       0.50      0.50      0.49         6

## Linear Support Vector Machine

###### SVM always tries to finde the best possible straight separation between clases

In [31]:
# possible hyper params, loss function, regularization
svm = SGDClassifier().fit(X_train, y_train)

In [32]:
y_pred_svm = svm.predict(X_test)

In [33]:
accuracy_score(y_pred_svm, y_test)

0.5

In [34]:
print(classification_report(y_test, y_pred_svm, zero_division=0))

              precision    recall  f1-score   support

    negative       0.50      0.33      0.40         3
    positive       0.50      0.67      0.57         3

    accuracy                           0.50         6
   macro avg       0.50      0.50      0.49         6
weighted avg       0.50      0.50      0.49         6